synolia_ajax_button_favorite:
    resource: '@SynoliaFavoriteBundle/Controller/Frontend/FavoriteButtonAjaxController.php'
    type: annotation
    prefix: /favorite
    options:
        frontend: true

synolia_favorite_index:
    resource: '@SynoliaFavoriteBundle/Controller/Frontend/FavoriteController.php'
    type: annotation
    prefix: /customer/favorite
    options:
        frontend: true
