services:

    Synolia\Bundle\FavoriteBundle\EventListener\FrontendProductSearchGridListener:
        arguments:
            - '@oro_security.token_accessor'
            - '@Synolia\Bundle\FavoriteBundle\Entity\Repository\FavoriteRepository'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.frontend-product-search-grid, method: onBuildBefore }
            - { name: kernel.event_listener, event: oro_datagrid.search_datasource.result.after.frontend-product-search-grid, method: onResultAfter }

    Synolia\Bundle\FavoriteBundle\EventListener\SynoliaFavoriteGridListener:
        arguments:
            - '@oro_security.token_accessor'
            - '@Synolia\Bundle\FavoriteBundle\Entity\Repository\FavoriteRepository'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.synolia-favorite-grid, method: onBuildAfter }
