services:
    Synolia\Bundle\FavoriteBundle\Layout\DataProvider\FavoriteDataProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_security.token_accessor'
        tags:
            - { name: layout.data_provider, alias: synolia_favorite }

    Synolia\Bundle\FavoriteBundle\Handler\FavoriteButtonAjaxHandler:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'

    Synolia\Bundle\FavoriteBundle\Twig\FavoriteExtension:
        arguments:
            - '@Synolia\Bundle\FavoriteBundle\Layout\DataProvider\FavoriteDataProvider'
        tags:
            - { name: twig.extension }

    Synolia\Bundle\FavoriteBundle\Layout\Extension\FavoriteAwareContextConfigurator:
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: layout.context_configurator }
